### PR TITLE
Attempt to fix GO_REBUILD_URSELF on Microsloth Windows

### PR DESCRIPTION
**Pull request by herrhotzenplotz**
Great type-safety in WinAPI I guess....

### CODE REVIEW

**Comment by herrhotzenplotz** [comment]
Sorry I didn't want to interject on stream for reasons :)

**Comment by zhiayang** [comment]
heck, you beat me to it

EDIT: this works on windows. Close #30

**Comment by rexim** [comment]
@herrhotzenplotz looks good to me! :+1: Thank you for your contribution!

**Comment by rexim** [comment]
@zhiayang thank you for testing it on windows!

**Pull request merged**
